### ISSUE TITLE
Recurring params

### ISSUE THREAD

**Issue by tonyfast** [redodo/tortilla#17]
It would be cool if ``api.param`` could recur like ``api.headers``.  The Tumblr and Github API's can accept the access key in the query string.

Currently, when I pass an access key I will:
```
api = tortilla.wrap('https://api.example.org')
api.video(id).comments.get(count, params={ 'token' : token})
```
I think it might be nice to be able to say when you may need to make a lot of requests
```
api = tortilla.wrap('https://api.example.org')
api.params.token = token
api.video(id).comments.get(count)
```

**Comment by redodo** [comment]
This is a good idea. It's included in the current pre-release.
