### ISSUE TITLE
adding delay between each request?

### ISSUE THREAD

**Issue by hbredin** [redodo/tortilla#18]
The API I am trying to use will reject my HTTP requests if they are too frequent (say, more than 5 requests per second).

Would it be possible to provide some kind of delay between each call when creating the wrapper?

```python
api = tortilla.wrap('https://github.com', delay=0.2)  # 200ms between each request
```

I am willing to write a pull request for this but I am not sure if I need to modify the `Client` or the `Wrap` class...

We could make a call to `self._pause()` defined below before each call:

```python
def pause(self):
    if self.delay > 0:
        current_time = time.time()
        elapsed = current_time - self.previous_call
        if elapsed < self.delay:
            time.sleep(self.delay - elapsed)
        self.previous_call = current_time
```

What do you think?

Another option would be to use an adapted version of the `retry` decorator defined here: https://wiki.python.org/moin/PythonDecoratorLibrary#Retry

**Comment by redodo** [comment]
This would be an interesting and useful addition.

It would be a change in the `request` method of the `Client` class, which will then save the timestamp of the last request and sleep the remaining time (if required) when the next request comes in. I'll have a look at it.

Until this is implemented, you could also use the caching functionality if you're only executing GET requests.
