### ISSUE TITLE
Client.request format impose same conversion for requests load and response

### ISSUE THREAD

**Issue by guglielmo** [redodo/tortilla#23]
There may be cases where a binary-data load must be sent along with the request, and a json response is received (for example, see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html).

It may be worth splitting the ``format`` option into ``req_format`` and ``resp_format``, both having "json" as default.

I guess, that having the response parsed from yml is not a very common use case, and that the need to pare responses different from json may point to XML, otherwise it could be possible to only specify the format for requests, and always parse response from json.

**Comment by redodo** [comment]
Added in dd5757f56921965d212f6bf64c0d163fefa96a90.
