### ISSUE TITLE
dependency on colorclass

### ISSUE THREAD

**Issue by medecau** [redodo/tortilla#28]
Please make the colorclass dependency optional.

It is useless in a server environment.
And services like AppEngine don't allow the use of ctypes which colorclass depends on.

**Comment by redodo** [comment]
Currently, I am not entirely sure how to approach this issue. I'd like the debug messages to remain colored by default and making a dependency optional would make this an opt-in. So, maybe it would be better to go for a colorclass-like library with wider support.

Do you have any suggestions on what library to use that would work in your situation?

**Comment by medecau** [comment]
There may be better alternatives but I only know of [Colorama](https://github.com/tartley/colorama).

I found Colorama from [clint](https://github.com/kennethreitz/clint) but I have seen it used in [click](https://github.com/pallets/click) too.

**Comment by redodo** [comment]
Alright, I will have a look.

**Comment by medecau** [comment]
Thank you.
