### ISSUE TITLE
RFI: Allow for defining external loads / dumps instead of Bunch.

### ISSUE THREAD

**Issue by ayoshi** [redodo/tortilla#5]
Could be set the same way headers are set for an endpoint, as an option.

This is useful for people using 'schematics' and the similar libraries to define validation and type coercion models.
There is no problem to run the model on a Bunch objects, but passing the loads/dumps has the following advantages:

1) Will remove an unnecessary level of an indirection.
2) Will allow to pass objects to post/patch  directly in their native validated format, without conversion to the dictionary ( will be performed by serializer the tortilla customer defines )
3) Will allow you not to support formats ( like XML and whatnot ) directly, passing the request straight to the wrapper/unwrapper callables.

This change can be backward compatible, setting JSON->Bunch as a default loads and Dict->JSON as dumps ( will match current behaviour ).

Output format will be up to tortilla customer, so providing he knows what API receive he will be able to provide the appropriate callables.

Example with schematics:

``` python
from schematics.models import Model, 
import tortilla
import json

register = tortilla.wrap('https://people_register.com')

Class Person(Model):
    name = StringType()
    age = IntType()

    def dumps(self):
        """ Dump JSON from Person """
        return json.dumps(self.to_primitive())

    @classmethod
    def loads(cls, json):
        """ Provided JSON return Person object """
        return Person(json.loads(json))

# Wrapper receives response and converts 
register.loads = Person.loads
register.dumps = Person.dumps

# Here we pass native object !
register.post(data=Person(name='John Doe', age=25))

# Here we will receive back Person object, validated !
person = register.get()
```

What do you think?

**Comment by redodo** [comment]
This has been added in v0.4.0.
